### ISSUE TITLE
Возникло исключение на уровне кода

### ISSUE THREAD

**Issue by Valiria-29** [Gidush/HospApp#1]
Новый доктор. 
Ввести  только ФИО, состоящее из цифр (1234)
Логин и пароль не вводить
Программа останавливается с System.ArgumentException
Ожидалось, что появится предупреждение о некорректном вводе данных
![image](https://user-images.githubusercontent.com/113546120/207661561-cce1bcea-8260-4be1-8857-8d706beb30d2.png)

**Comment by Misterychonui** [comment]
Спасибо за обратную связь. Поставили ограничения на ввод пустых полей. ФИО состоящее из цифр и других наборов символов мы считаем приемлемым.  Мы не дискриминируем людей с нестандартными данными
