### ISSUE TITLE
Значение поля СНИЛС равное 000-000-00 00 принимается как корректное

### ISSUE THREAD

**Issue by Valiria-29** [Gidush/HospApp#2]
Режим врача. Если выполнить вход через зарегистрированную учетную запись врача, и  зарегистрировать нового пациента с СНИЛС 000-000-00 00, то это значение принимается как корректное.
Ожидалось, что появится предупреждение о некорректности данного поля.

**Comment by Gidush** [comment]
Спасибо за за обратную связь, недочёт исправлен, можете вытянуть изменения!
